### ISSUE TITLE
Final submission Project Proposal of Group_D_Nutrition

### ISSUE THREAD

**Issue by QinyaoXia** [qmss-gr5063-2019/Group_D_Nutrition#1]
352312ca8c57b891ecb439aeab2bdc0367e02ea2
@eddiecylin @JiaxiYang1992 @tbrambor

**Comment by tbrambor** [comment]
Comments for the Group:

The idea of studying obesity and nutrition is worthwhile. Your data sources are reasonably rich but the visualization choices of leave the user with uninformative plots and poor communication of your results. Many times, the use of maps to make your points are ill-chosen to bring the point across. For example, the use of maps to compare activity rates and veggie intake vs. a plot of fast food restaurant locations is unhelpful. I am not sure what I could take away from this, beside the location dispersion in the U.S. and perhaps the popularity of these four fast food chains. In both cases, it would be better to provide a scatter plot (or similar) showing each of these variables vs. obesity rates — the original intention of the project. The analysis of tweets has potential but appears to suffer from data sparsity or analysis issues. For example, why are we getting polarity numbers of 0 and 1 across entire states. Is the data so sparse that we get average (?) polarity scores at the extremes? 
This project has potential but many things would need to be improved to fully explore and visualize  the information in the datasets.

Overall Grade: B
